project:
  type: website
  output-dir: docs

website:
  title: "GIS Resources for Animal Movement Studies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Software.html
        text: Software
      - href: Basemaps.html
        text: Basemaps
      - href: Projections.hml
        text: Projections
      - href: Tracking_Data.html
        text: Tracking Data
      - href: Static_Data.qmd
        text: Static Data
      - href: Dynamic_Data.qmd
        text: Dynamic Data
      - href: Polar_Regions.html
        text: Polar regions 
      - href: Tutorials.qmd
        text: Tutorials   

    right:
      - icon: github
        href: https://github.com/E-Honan/GIS-Resources

format:
  html:
    theme: sketchy
    toc: true
    
    
    
    
    
    
    
    
    
    
    
  