project:
  type: website
  output-dir: docs

website:
  title: "GIS Resources for Animal Movement Studies"
  search: TRUE
  page-footer: "Eleanor Maedhbh Honan 2026" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projections.html
        text: Projections
      - href: Software.html
        text: Software
      - href: Basemaps.qmd
        text: Basemaps
      - href: Tracking_Data.html
        text: Tracking Data
      - href: Environmental_Data.qmd
        text: Environmental Data
      - href: Polar_Regions.html
        text: Polar Regions 
      - href: Tutorials.qmd
        text: Tutorials & Design
    #  - test.qmd
      

    right:
      - icon: github
        href: https://github.com/E-Honan/GIS-Resources

 
format:
  html:
    theme: sketchy
    linkcolor: "#471C5E"
    toc: true
    

    
    
    
    
  
    
    
    





    
    
    
    
    
    
    
    
    
    
    
    
  