---
title: "Environmental Data"
editor: visual
---

In our practical sessions, we've used various types of **environmental** data. These data have either been static or dynamic.

**Static** environmental data layers are those that are (relatively) fixed - think water depth or outlines of countries. In reality, the whims of plate tectonics and geopolitics mean there are no truly 'fixed' data layers, but for the purpose of making maps or conducting analyses we consider them as permanent.

In contrast, **dynamic** environmental layers are those that vary temporally. For example, the temperature of the ocean's surface in a given area will vary across different timescales - usually with small differences between days, but greater differences between weeks or months.

In practice, this means that if you wanted to see if animals used different water depths over the course of a breeding season, you could use the same file for depth for everyday of the breeding season. However, if you wanted to see if they used warmer or colder waters throughout the breeding season, you would need a different file of sea surface temperature for everyday of your study period.

What data product you use will vary based on the resolution of data required to answer your question. If you're curious of how close to the sea-ice edge Emperor penguins forage in Antarctica, you might use a relatively course sea-ice edge product - one of the most frequently used is at a scale of 25km^2,^ as the penguins' foraging trips can span 100s of kilometers. You would also want a product with a near-daily resolution. However, if you wanted to see how a mangrove boundry changed over the course of a year in a small inlet in Indonesia, you would want a much higher resolution image, potentially sub-meter in scale, and monthly imagery would suffice.

Here, I've listed some portals for where you can access environmental data. They are all free to access, but most will require you to make an account. I haven't separated them out by the type of data, as many of the portals host multiple types of environmental data, encompassing both oceans and land.

## **Where to find environmental data:** 
